import Head from "next/head";
import React from "react";

const AppHeader = () => {
  return (
    <Head>
      <title>Mapbox GL JS - Next.js</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default AppHeader;
